### ISSUE TITLE
Set compiler-dependent behaviour for float parsing 

### ISSUE THREAD

**Issue by jackalcooper** [ityonemo/zig_parser#2]
- error
```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of a float

    :erlang.binary_to_float("1.18973149535723176502e+4932")
    (zig_parser 0.1.3) lib/zig.parser/collected.ex:49: Zig.Parser.Collected.post_traverse/6
Warning:     (zig_parser 0.1.3) Zig.Parser."FLOAT__45"/6
    (zig_parser 0.1.3) Zig.Parser."PrimaryTypeExpr__43"/6
    (zig_parser 0.1.3) Zig.Parser."SuffixExpr__2"/6
    (zig_parser 0.1.3) Zig.Parser."ErrorUnionExpr__0"/6
    (zig_parser 0.1.3) Zig.Parser."TypeExpr__6"/6
    (zig_parser 0.1.3) Zig.Parser."CurlySuffixExpr__0"/6
```
- zig source:
[translate.out.zig.txt](https://github.com/ityonemo/zig_parser/files/10299440/translate.out.zig.txt)

**Comment by ityonemo** [comment]
oh wow, that one is tricky.

**Comment by ityonemo** [comment]
fixed in https://github.com/ityonemo/zig_parser/commit/8f26f78079e5adb244ea20dd2fb0b603db141830

**Comment by jackalcooper** [comment]
@ityonemo after updating to 0.1.5, it is not fixed. The expression:

```
pub const __LDBL_MAX__ = @as(c_longdouble, 1.18973149535723176502e+4932);
```

Maybe the float parser used in type expression is not the one updated in the last commit?

**Comment by ityonemo** [comment]
Ok so I checked hex diff, and the change is in there:  https://diff.hex.pm/diff/zig_parser/0.1.4..0.1.5

and if I run this on the console on my local machine it seems to work, can your get a minimal reproduction on 0.1.5?

```
ityonemo@pop-os:~/code/zig_parser$ iex -S mix
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Zig.Parser.parse("pub const __LDBL_MAX__ = @as(c_longdouble, 1.18973149535723176502e+4932);")
%Zig.Parser{
  doc_comment: nil,
  code: [
    {:const,
     %Zig.Parser.ConstOptions{
       position: %{column: 5, line: 1, offset: 0},
       doc_comment: nil,
       pub: true,
       comptime: false
     },
     {:__LDBL_MAX__, nil,
      {:builtin, :as,
       [:c_longdouble, {:extended_float, "1.18973149535723176502e+4932"}]}}}
  ],
  dependencies: [],
  comments: []
}
```

**Comment by ityonemo** [comment]
note that I've tagged it `:extended_float` in the case the float parser couldn't convert it into an IEEE-754 f64.

**Comment by jackalcooper** [comment]
I found the problem. I was running elixir 1.3 in the github action. In elixir 1.4 this has beem fixed by this PR: https://github.com/elixir-lang/elixir/pull/12099/files

**Comment by ityonemo** [comment]
Oh wow.  I should probably pin elixir versions!

**Comment by ityonemo** [comment]
not compiler-dependent, but fixed here:

https://github.com/ityonemo/zig_parser/commit/036e953813673e849cb05c53951b39f3a441c185

**Comment by jackalcooper** [comment]
👍
